package io.getarrays.securecapita.roles.prerunner;

public enum ROLE_AUTH {
    READ_USER,
    UPDATE_USER,
    CREATE_ASSET,
    VIEW_ASSET,
    VIEW_STATION,
    CREATE_STATION,
    ASSIGN_STATION,
    ASSIGN_ROLE,
    CREATE_PRODUCT,
    ALL_STATION,
    CREATE_PURCHASEREQUEST,
    CHECK_ASSET,
    REQUEST_MOVE_ASSET,
    APPROVE_MOVE_ASSET;

}
